name: Chromecast
favicon: null
layout_spectrum: 0.22158
typography_spectrum: 0.73815
title: Chromecast Backgrounds
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#e33e2b'
    - '#2ca24c'
    - '#f1b500'
    - '#a7c0f0'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
