name: Chromecast
favicon: null
layout_spectrum: 0.3890517584513873
typography_spectrum: 0.023693618830293417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8430985386949033
  lightness: 0.8609274700284004
  saturation: 0.7556480937637389
  rhythmicContrast: 0.15486387023702264
purpose: []
